### ISSUE TITLE
Make gocept.jsform a NPM package.

### ISSUE THREAD

**Issue by sweh** [sweh/ajja#43]
Originally reported by: **sweh (Bitbucket: [sweh](http://bitbucket.org/sweh), GitHub: [sweh](http://github.com/sweh))**

---

Follows #42.

gocept.jsform should become a NPM package. One main benefit is that we can use `require` to include local and external resources and we can use gocept.jsform as a resource in other NPM based packages.

In order to stay compatible with bower, which we use as the package manager for the browser, we need a compile step for grunt (e.g. browserify or webpack).

---
- Bitbucket: https://bitbucket.org/gocept/gocept.jsform/issue/43

**Comment by florianpilz** [comment]
@sweh: Do we have a NPM package now or was this closed as `wontfix`, since the library does not make sense in the backend?

**Comment by sweh** [comment]
gocept.jsform is an NPM package now. If we should publish it to the NPM package manager is another question and out of the scope of this ticket.
